# Generated by Django 4.2.7 on 2025-07-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField()),
                ('variant', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('operating_hours', models.CharField(max_length=100)),
                ('delivery_radius', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField()),
            ],
        ),
    ]
